# This is a docker compose file for running development tools (building, dev server) in containers.
# It is designed to mount this development environment directly and work over it.
# If you want to run a static build and development deployment, see docker-compose.yml instead.
# If you want to do a production deployment, see the deployment folder instead.

# Generally you would want to run this via the `npm run` scripts in the relevant package.json files for the projects.
# Running this directly will require setting environment variables:
# USER_ID: The id of the user running this (used so files created in the containers have the right permissions.)
# GROUP_ID: The id of the group of the user running this (used so files created in the containers have the right permissions.)
# ROOT_DIR: The root directory of the massive decks repository you are working in (work around docker compose issues).

networks:
  porty_default:
    name: porty_default
    external: true

services:
  client:
    build:
      context: "./client/dev"
    user: "1000:1000"
    ports:
      - "28080:8080/tcp"
    volumes:
      - /share/CACHEDEV1_DATA/docker/appdata/massivedecks/client:/md/client
    networks:
      - porty_default

  server:
    build:
      context: "./server/dev"
    user: "1000:1000"
    volumes:
      - /share/CACHEDEV1_DATA/docker/appdata/massivedecks/server:/md/server
    networks:
      - porty_default
